# Generated by Django 5.1.4 on 2024-12-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='references',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('references', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'references',
            },
        ),
    ]
