# Generated by Django 5.1.4 on 2024-12-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_references_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='academic_yr',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='reference',
            name='coursecode',
            field=models.TextField(default='Unknown'),
        ),
    ]
