# Generated by Django 5.1.4 on 2024-12-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_reference_academic_yr_reference_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='academic_yr',
            field=models.CharField(default='2024-25', max_length=9),
        ),
    ]
